### ISSUE TITLE
Exhausted ballots still count towards total for deciding majorities

### ISSUE THREAD

**Issue by timotree3** [LivingInSyn/rcir#1]
Consider this set of ballots:

- Alice, Sam
- Bob, Sam
- Chris, Bob
- Sam, Chris
- Alice, Chris

Let's see what we get by doing an Instant-runoff vote by hand.

1. Eliminate last place candidates:
    - Alice, ___
    - ___, ___
    - ___, ___
    - ___, ___
    - Alice, ___
2. Is there a majority out of the ballots that still have votes? Yes, Alice should win with a 2/2 majority.

Our implementation gives a different result. It counts ballots that don't have any votes left and in this case finds that Alice would need at least a 3/5 majority to win.

**Comment by LivingInSyn** [comment]
You're right. This behavior should be configurable

**Comment by timotree3** [comment]
> You're right. This behavior should be configurable

I'm glad you agree. 

Regarding configuration I can't think of a use case where someone would prefer the current output (which is `Err(ElectionError::VotersNoVotes)`).

It seems like in order to meet user's expectations given [how other sources define the algorithm][1] it should instead return a winner (in this example `Ok("alice")`).

What do you think?

[1]: https://en.wikipedia.org/wiki/Instant-runoff_voting#Election_procedure

**Comment by LivingInSyn** [comment]
Hey, check out this branch:

https://github.com/LivingInSyn/rcir/commit/3f433f9d52ffd4f59b8ea38465f6090f4a53d115

Basically, I added a mode where you can operate under a 'complete majority' mode, by which you have to have >= 50% of all of the voters in agreement, or 'remaining majority' mode, where you need >= 50% of the non-empty voters

This doesn't fix the great `VotersNoVotes` error name, but I'll try and come up with a fix for that tomorrow

**Comment by LivingInSyn** [comment]
Closed in favor of: 

https://github.com/LivingInSyn/rcir/pull/4

**Comment by timotree3** [comment]
Cool. I'm still not clear what use case people would want to use the CompleteMajority mode. It's good for there to be a RemainingMajority option either way though. :)
